server:
  port: ${PORT:8011}   
  
eureka:        
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
      healthcheck:
       enabled: true
       lease:
          duration: 5
management:
    endpoints:
     web:
      exposure:
       include : "*"
       exclude : "loggers"
    endpoint:
     shutdown:
       enabled: true
   

  
logging:
  level:
    com.kotesh: DEBUG